---
services:
    tag_management:
        service_name: 'tag-management'
        url: '/api/space/tag-management'

    device_management:
        service_name: 'device-management'
        url: '/api/space/device-management'
...